version: '2'
volumes:
    sense-data:
    dashboard-data:
services:
  influxdb:  #ORIGINAL
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  dashboard:  #BLOCK replaces grafana
    image: ./dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '80'
  sensor:  #ORIGINAL
    build: ./sensor
    privileged: true
    restart: always
    volumes:
      - 'sense-data:/data'
    expose:  # ADDED
      - '7575'
  connector: #BLOCK replaces telegraf
    image: balenablocks/connector:raspberrypi3
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
    ports:
      - "8080" # only necessary if using ExternalHttpListener (see below)
  mqtt:  #ORIGINAL
    image: arm32v6/eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always
